use crate::generator::ForeignFunctions;
use anyhow::{Result, bail};
use askama::Template;
use quote::__private::TokenStream;
use quote::{format_ident, quote};
use std::fs;
use std::path::Path;

fn snake_to_camel(s: &str) -> String {
    let mut result = String::with_capacity(s.len());
    let mut capitalize_next = true;

    for c in s.chars() {
        if c == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(c.to_ascii_lowercase());
        }
    }

    result
}

fn generate_dispatcher_tokens(foreign_functions: &ForeignFunctions) -> Result<TokenStream> {
    let mut structs_tokens = Vec::new();
    let mut match_arms_token = Vec::new();
    let mut structs_names = Vec::new();
    for (i, fn_sign) in foreign_functions.deferred.iter() {
        let fn_ident = &fn_sign.ident;

        let mut struct_fields = Vec::new();
        let mut struct_fields_idents = Vec::new();
        for sign in fn_sign.inputs.iter() {
            if let syn::FnArg::Typed(arg) = sign {
                let arg_ident = if let syn::Pat::Ident(pat_ident) = &*arg.pat {
                    &pat_ident.ident
                } else {
                    bail!(
                        "Unsupported argument pattern in function signature: {:?}",
                        fn_sign
                    )
                };

                let ty = &arg.ty;

                if let syn::Type::Reference(_) = **ty {
                    bail!(
                        "jconduit commands cannot accept Rust references (&T). Use raw pointers (*const T) for zero-copy data."
                    );
                };

                struct_fields_idents.push(arg_ident);

                struct_fields.push(quote! {
                    pub #arg_ident: #ty
                })
            }
        }

        let struct_name = format_ident!("Command{}", snake_to_camel(&fn_ident.to_string()));
        structs_tokens.push(quote! {
            #[repr(C)]
            pub struct #struct_name {
                #(#struct_fields,)*
            }
        });
        structs_names.push(struct_name.clone());

        let j = *i;
        let arm = if !fn_sign.inputs.is_empty() {
            quote! {
                #j => {
                    unsafe {
                        let ptr = payload_ptr as *const #struct_name;
                        let cmd = &*ptr;

                        #fn_ident( #(cmd.#struct_fields_idents),* );
                        size_of::<#struct_name>()
                    }
                }
            }
        } else {
            quote! {
                #j => {
                    unsafe {
                        #fn_ident( #(cmd.#struct_fields_idents),* );
                        0
                    }
                }
            }
        };

        match_arms_token.push(arm);
    }

    let mut direct_functions = Vec::new();
    for fn_sign in foreign_functions.direct.iter() {
        let fn_ident = &fn_sign.ident;
        let mut fn_args_names = Vec::new();
        let mut fn_args_types = Vec::new();

        let mut unsafe_token = quote! {};

        for input_sign in fn_sign.inputs.iter() {
            if let syn::FnArg::Typed(arg) = input_sign {
                let arg_ident = if let syn::Pat::Ident(pat_ident) = &*arg.pat {
                    &pat_ident.ident
                } else {
                    bail!(
                        "Unsupported argument pattern in function signature: {:?}",
                        fn_sign
                    )
                };

                let ty = &arg.ty;

                if let syn::Type::Reference(_) = **ty {
                    bail!(
                        "jconduit commands cannot accept Rust references (&T). Use raw pointers (*const T) for zero-copy data."
                    );
                };

                if matches!(&**ty, syn::Type::Ptr(_)) {
                    unsafe_token = quote! {unsafe};
                }

                fn_args_names.push(quote! {#arg_ident});
                fn_args_types.push(quote! {#ty});
            }
        }

        let (fn_return_type_token, fn_return_column) = match &fn_sign.output {
            syn::ReturnType::Default => (quote! {}, quote! {;}),
            syn::ReturnType::Type(_, ty) => (quote! { -> #ty }, quote! {}),
        };

        let prefixed_ident = format_ident!("jconduit_{}", fn_ident);

        let direct_call = quote! {
            #[unsafe(no_mangle)]
            pub #unsafe_token extern "C" fn #prefixed_ident( #( #fn_args_names: #fn_args_types ),* ) #fn_return_type_token {
                unsafe{ crate::ffi::#fn_ident( #( #fn_args_names ),* )#fn_return_column}
            }
        };

        direct_functions.push(direct_call);
    }

    let version = env!("CARGO_PKG_VERSION");
    let comment_string = format!(
        " Automatically generated by Jconduit v{}. Changes will be overwritten if the file is regenerated.",
        version
    );

    let result = quote! {

        #![allow(clippy::too_many_arguments)]
        use crate::ffi::*;


        #[doc=#comment_string]

        #(#structs_tokens)*


        #[allow(dead_code)]
        #[unsafe(no_mangle)]
        pub extern "C" fn __jconduit_anchor(
            #(_: *const #structs_names),*
        ) {}


        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn flush_buffer(buffer_ptr: *mut u8) {
            if buffer_ptr.is_null() { return; }

            let command_count = unsafe { *(buffer_ptr as *const u32) };
            if command_count == 0 { return; }

            let mut cursor = unsafe{buffer_ptr.add(4)};

            for _ in 0..command_count {
                // 1. Calculate padding
                let padding_required = (-(cursor as isize + 4) as usize) & 15usize;
                // 2. Advance the cursor
                cursor = unsafe { cursor.add(padding_required) };
                // 3. Read the command id
                let command_id = unsafe { *(cursor as *const u32) };
                // 4. Advance the cursor to the payload
                cursor = unsafe { cursor.add(4) };
                // 5. Dispatch the command
                let payload_size = dispatch_command(cursor, command_id);
                // 6. Advance the cursor by the command payload size
                cursor = unsafe { cursor.add(payload_size) };
            }
        }

         fn dispatch_command(payload_ptr: *const u8, command_id: u32) -> usize {
            match command_id {
                #(#match_arms_token)*
                _ => panic!("No command with id: {}", command_id),
            }
        }

        #(#direct_functions)*
    };

    Ok(result)
}

#[derive(Template)]
#[template(path = "cargo.toml.askama")]
struct CargoTomTemplate {
    crate_name: String,
    lib_name: String,
    version: String,
}
pub(super) fn crate_gen(name: &str, version: &str, crate_path: &Path) -> Result<()> {
    let root_tokens = quote! {
        pub mod ffi;
        pub mod dispatch;
    };

    let cargo_toml_path = crate_path.join("Cargo.toml");

    let lib_name = name.replace('-', "_");

    let toml_template = CargoTomTemplate {
        crate_name: name.to_string(),
        lib_name: lib_name.to_string(),
        version: version.to_string(),
    };

    fs::write(&cargo_toml_path, &toml_template.render()?)?;

    let syntax_tree: syn::File = syn::parse2(root_tokens)?;
    let pretty_code = prettyplease::unparse(&syntax_tree);
    fs::create_dir_all(crate_path.join("src"))?;
    fs::write(crate_path.join("src/lib.rs"), pretty_code)?;

    Ok(())
}
pub fn generate_dispatcher(
    dispatcher_file: &Path,
    foreign_functions: &ForeignFunctions,
) -> Result<()> {
    let dispatcher_tokens = generate_dispatcher_tokens(foreign_functions)?;
    let syntax_tree: syn::File = syn::parse2(dispatcher_tokens)?;
    let pretty_code = prettyplease::unparse(&syntax_tree);
    fs::write(dispatcher_file, pretty_code)?;

    Ok(())
}
