use crate::ir::{InterRepr, IrType, IrTypeKind, PrimitiveType};
use crate::utils::formatting::{Writer, to_pascal_case};
use std::fs;
use std::path::Path;
use std::process::Command;
use thiserror::Error;

#[derive(Debug, Error, PartialEq, Eq)]
pub enum JextractError {
    #[error("Failed to find jextract executable")]
    JextractNotFound,
    #[error("Failed to generate jextract bindings")]
    JextractFailed,
    #[error("Failed to create output directory")]
    CannotGenerateFolder,
    #[error("Failed to write header file")]
    FailedToWriteHeader,
}

pub fn map_primitive_to_c(p: &PrimitiveType) -> &'static str {
    match p {
        PrimitiveType::Void => "void",
        PrimitiveType::Bool => "bool",
        PrimitiveType::U8 => "uint8_t",
        PrimitiveType::I8 => "int8_t",
        PrimitiveType::U16 => "uint16_t",
        PrimitiveType::I16 => "int16_t",
        PrimitiveType::U32 => "uint32_t",
        PrimitiveType::I32 => "int32_t",
        PrimitiveType::U64 => "uint64_t",
        PrimitiveType::I64 => "int64_t",
        PrimitiveType::Float => "float",
        PrimitiveType::Double => "double",
        PrimitiveType::SizeT => "size_t",
        PrimitiveType::SsizeT => "ssize_t",
        PrimitiveType::PtrDiffT => "ptrdiff_t",
        PrimitiveType::Uptr => "uintptr_t",
        PrimitiveType::Iptr => "intptr_t",
        PrimitiveType::Wchar => "wchar_t",
    }
}

pub fn format_c_declaration(ir_type: &IrType, name: &str) -> String {
    match &ir_type.kind {
        IrTypeKind::Primitive(p) => {
            let base = map_primitive_to_c(p);
            if ir_type.is_base_const {
                if name.is_empty() {
                    format!("const {base}")
                } else {
                    format!("const {base} {name}")
                }
            } else {
                if name.is_empty() {
                    base.to_string()
                } else {
                    format!("{base} {name}")
                }
            }
        }
        IrTypeKind::Named(s) => {
            if ir_type.is_base_const {
                if name.is_empty() {
                    format!("const {s}")
                } else {
                    format!("const {s} {name}")
                }
            } else {
                if name.is_empty() {
                    s.clone()
                } else {
                    format!("{s} {name}")
                }
            }
        }

        IrTypeKind::Pointer { to, is_ptr_const } => {
            let new_name = if name.is_empty() {
                if *is_ptr_const { "* const" } else { "*" }.to_string()
            } else {
                if *is_ptr_const {
                    format!("* const {name}")
                } else {
                    format!("*{name}")
                }
            };
            format_c_declaration(to, &new_name)
        }

        IrTypeKind::Reference { to } => {
            let new_name = if name.is_empty() {
                "*".to_string()
            } else {
                format!("*{name}")
            };
            format_c_declaration(to, &new_name)
        }

        IrTypeKind::FixedArray { element_type, size } => {
            let new_name = if name.is_empty() {
                format!("[{size}]")
            } else if name.starts_with('*') {
                format!("({name})[{size}]")
            } else {
                format!("{name}[{size}]")
            };
            format_c_declaration(element_type, &new_name)
        }

        IrTypeKind::FunctionPointer {
            return_type,
            arguments,
        } => {
            let args_string = arguments
                .iter()
                .map(|arg| format_c_declaration(arg, ""))
                .collect::<Vec<_>>()
                .join(", ");

            let func_name = if name.is_empty() {
                format!("(*)({args_string})")
            } else if name.starts_with('*') {
                format!("({name})({args_string})")
            } else {
                format!("(*{name})({args_string})")
            };

            format_c_declaration(return_type, &func_name)
        }
    }
}

fn generate_c_header(ir: &InterRepr) -> String {
    let mut w = Writer::new();
    w.line("// Automatically generated by JConduit");
    w.line("#pragma once");
    w.line("#include <stdint.h>");
    w.line("#include <stdbool.h>");
    w.line("");

    for e in ir.enums.values() {
        w.line("typedef enum {");
        w.indent();

        for variant in &e.variants {
            w.line(&format!("{} = {},", variant.name, variant.value));
        }

        w.dedent();
        w.line(&format!("}} {};", e.name));
        w.line("");
    }

    for s in ir.structs.values() {
        w.line("typedef struct {");
        w.indent();
        for field in &s.fields {
            let decl = format_c_declaration(&field.ty, &field.name);
            w.line(&format!("{};", decl));
        }
        w.dedent();
        w.line(&format!("}} {};", s.name));
        w.line("");
    }

    for (_command_id, func) in ir.deferred_functions.values() {
        if func.params.is_empty() {
            continue;
        }

        let pascal_name = to_pascal_case(&func.name);
        let struct_name = format!("Func{}", pascal_name);

        w.line("typedef struct {");
        w.indent();

        for param in &func.params {
            let decl = format_c_declaration(&param.ty, &param.name);
            w.line(&format!("{};", decl));
        }

        w.dedent();
        w.line(&format!("}} {};", struct_name));
        w.line("");
    }

    w.line("void flush_buffer(uint8_t* buffer_ptr);");

    w.finish()
}

fn jxt_bindings(
    jxt_package: &str,
    jxt_class_name: &str,
    header_path: &Path,
    java_dir: &Path,
) -> Result<(), JextractError> {
    #[cfg(target_os = "windows")]
    const JEXTRACT_CMD: &str = "jextract.bat";

    #[cfg(any(target_os = "linux", target_os = "macos"))]
    const JEXTRACT_CMD: &str = "jextract";

    Command::new(JEXTRACT_CMD)
        .arg("--version")
        .output()
        .map_err(|_| JextractError::JextractNotFound)?;

    Command::new(JEXTRACT_CMD)
        .arg("--output")
        .arg(java_dir)
        .arg("--target-package")
        .arg(jxt_package)
        .arg("--header-class-name")
        .arg(jxt_class_name)
        .arg(header_path)
        .output()
        .map_err(|_| JextractError::JextractFailed)?;

    Ok(())
}

pub fn gen_jxt_bindings(
    ir: &InterRepr,
    jxt_package: &str,
    jxt_class_name: &str,
    java_dir: &Path,
) -> Result<(), JextractError> {
    let c_header_content = generate_c_header(ir);

    let header_output_path = &java_dir
        .parent()
        .unwrap()
        .join("include")
        .join("jextract.h");

    if let Some(parent) = header_output_path.parent() {
        fs::create_dir_all(parent).map_err(|_| JextractError::CannotGenerateFolder)?;
    }
    fs::write(header_output_path, c_header_content)
        .map_err(|_| JextractError::FailedToWriteHeader)?;

    jxt_bindings(jxt_package, jxt_class_name, header_output_path, java_dir)?;

    Ok(())
}
