name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test_and_lint:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Verify Code Formatting
        run: cargo fmt --check

      - name: Execute Cargo Tests
        run: cargo check --locked --all-features

      - name: Run Clippy Linter
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Execute Cargo Tests
        run: cargo test --all-features --locked